### ISSUE TITLE
Network is unavailable.

### ISSUE THREAD

**Issue by kricklen** [yhcting/netmbuddy#11]
When switching off wlan you say Network is unavailable when searching youtube, even though mobile data is still on. Is this intentional, or is there something wrong on my side?

**Comment by sbliven** [comment]
I get the above message with mobile data, and "error in accessing network" with wiki. Something must be broken. (Sony z3 compact, Android 1.6)

**Comment by glitchphan** [comment]
The one that was starred on F-Droid was the previous version. I tapped and installed the latest version. Still got the error, but then turned on WiFi only in the settings and exited/killed the app. After starting it again and turing off the WiFi only option, it works.

**Comment by kricklen** [comment]
Yes, the starred version in F-Droid seems to be old, the latest one 1.2.14 works with mobile data.
