### ISSUE TITLE
Most Youtube videos don't play for me

### ISSUE THREAD

**Issue by d33tah** [yhcting/netmbuddy#3]
Hi,

I downloaded the latest NetMBuddy from F-Droid and tried to watch some Youtube videos. I entered "cranberries" into the search and tried to see "The Cranberries - Zombie" from their VEVO. I immediately saw "playing done" and logcat shows the following error:

<pre>
W/ResponseProcessCookies(  787): Invalid cookie header: "Set-Cookie: VISITOR_INFO1_LIVE=hLkzVy3bDhc; path=/; domain=.youtube.com; expires=Tue, 14-Oct-2014 08:51:24 GMT". Unable to parse expires attribute: Tue
W/ResponseProcessCookies(  787): Invalid cookie header: "Set-Cookie: PREF=f1=50000000; path=/; domain=.youtube.com; expires=Tue, 14-Oct-2014 08:51:24 GMT". Unable to parse expires attribute: Tue
D/dalvikvm(  787): GC_CONCURRENT freed 518K, 46% free 4496K/8263K, external 1117K/1544K, paused 5ms+6ms
I/dalvikvm(  787): Jit: resizing JitTable from 1024 to 2048
D/dalvikvm(  787): GC_CONCURRENT freed 1435K, 53% free 3965K/8263K, external 1138K/1544K, paused 4ms+5ms
I/StagefrightPlayer(  138): setDataSource('http://r2---sn-uvt5-ajwe.googlevideo.com/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl')
I/NuHTTPDataSource(  138): connect to r2---sn-uvt5-ajwe.googlevideo.com:80/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl @0
I/AwesomePlayer(  138): mConnectingDataSource->connect() returned -1004
E/MediaPlayer(  787): error (1, -1004)
E/MediaPlayer(  787): Error (1,-1004)
I/StagefrightPlayer(  138): setDataSource('http://r2---sn-uvt5-ajwe.googlevideo.com/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl')
I/NuHTTPDataSource(  138): connect to r2---sn-uvt5-ajwe.googlevideo.com:80/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl @0
I/AwesomePlayer(  138): mConnectingDataSource->connect() returned -1004
E/MediaPlayer(  787): error (1, -1004)
E/MediaPlayer(  787): Error (1,-1004)
I/StagefrightPlayer(  138): setDataSource('http://r2---sn-uvt5-ajwe.googlevideo.com/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl')
D/dalvikvm(  326): GC_CONCURRENT freed 378K, 48% free 3167K/6087K, external 638K/1023K, paused 4ms+42ms
I/NuHTTPDataSource(  138): connect to r2---sn-uvt5-ajwe.googlevideo.com:80/videoplayback?ratebypass=yes&sver=3&mt=1392238650&expire=1392261303&key=yt5&id=e848e06b890952db&mv=m&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&ipbits=0&ip=77.237.11.50&itag=18&fexp=927905%2C928025%2C914072%2C916626%2C902533%2C937417%2C913434%2C936910%2C936913&ms=au&source=youtube&upn=BJOD28vzJp0&gcr=pl @0
I/AwesomePlayer(  138): mConnectingDataSource->connect() returned -1004
E/MediaPlayer(  787): error (1, -1004)
E/MediaPlayer(  787): Error (1,-1004)
V/lights  (  228): set_light_buttons state->color = -16777216 is_lit = 0
V/lights  (  228): write_int: path /sys/class/leds/button-backlight/brightness, value 0
D/droidparts-battery-widget(  692): battery state: level=77, charging=true
D/droidparts-battery-widget(  692): widgets updated
</pre>

Generally, most of the youtube videos don't seem to work, not sure if all of these are from Vevo.

**Comment by yhcting** [comment]
I can't reproduce this issue.
