### ISSUE TITLE
Some Video can't play

### ISSUE THREAD

**Issue by CloudedDragon** [yhcting/netmbuddy#4]
Dear yhcting:

Netmbuddy is a very good youtube hacking project.

But I meet some problems, there are some videos  can't play.
For example: 
PSY - HANGOVER feat. Snoop Dogg M/V
https://www.youtube.com/watch?v=HkMNOlYcpHg

I got the url form netmbuddy code as follow:
http://r7---sn-ipoxu-u2xe.googlevideo.com/videoplayback?mt=1402392314&gcr=tw&mv=m&pcm2=yes&ipbits=0&ratebypass=yes&sparams=gcr%2Cid%2Cip%2Cipbits%2Citag%2Cpcm2%2Cratebypass%2Csource%2Cupn%2Cexpire&source=youtube&ms=au&fexp=906010%2C912300%2C913434%2C923341%2C923445%2C924203%2C930008%2C932617%2C933111%2C934026%2C945049%2C948102&expire=1402415572&sver=3&ip=114.32.29.226&key=yt5&mws=yes&upn=9MzzCmgQVe4&id=o-AF_vu2AP59DAZnEB-nwUJMS39ZFXLUMfPI4J_9ZSEZJ8&itag=18

It means the YTHacker.Java need to revise??

**Comment by yhcting** [comment]
Sorry for late and lazy maintenance.
If issue is still reproducible, please reopen it.
Actually, some videos can't be played due to some constraints (regional restriction, license and so on.)
