### ISSUE TITLE
Title and control buttons overlapping

### ISSUE THREAD

**Issue by Code7R** [yhcting/netmbuddy#6]
![screenshot_2015-03-21-07-25-14](https://cloud.githubusercontent.com/assets/10660264/6765275/1d25ba14-cfd9-11e4-9143-7f9e628c586e.png)

I am not sure how it should look like but on my mobile, it looks weird. The control buttons overlap the title in the area at the bottom.

I am running the current version from F-Droid on latest CM11 for Sony Xperia Z1Compact.

**Comment by yhcting** [comment]
I'm sorry to say that this is my preference...
(It is working as designed)

**Comment by Code7R** [comment]
Seriously? I see controls and I see something drawn over them. For a lame user, this means that something is in your way when you want to touch control buttons.
