### ISSUE TITLE
Error in accessing network

### ISSUE THREAD

**Issue by SethArchambault** [yhcting/netmbuddy#9]
I get the error "error in accessing network" when using the search YouTube function.

**Comment by CraigsBar** [comment]
Me too. HTC one m8 with cm13.

**Comment by tastytea** [comment]
I have the same Problem.
Android 5.1.1 CM 12.1

**Comment by ericfont** [comment]
I'm getting this error right now on both my Samsug S3 international and tmboile phones, runnign cyangoenmod 13 nightly & 12.1 nightly.

**Comment by francocurotto** [comment]
Same error after reinstalling in xperia M

**Comment by glitchphan** [comment]
I guess this app doesn't work anymore?

**Comment by francocurotto** [comment]
I found the error. Apparently when you install the app from F-Droid, it installs an older version of NetMBuddy (1.2.11-1) if you just press the button install. What I did is simply selected the newest version (1.2.14) to install and it works perfectly.

**Comment by ericfont** [comment]
I can verify what francocurotto said works on my phone.  I noticed that 1.2.11-1 was starred.  And FDroid app by default will install the starred version.  So I think someone needs to tell FDroid to have the latest version be starred.

**Comment by glitchphan** [comment]
Good call.

**Comment by yhcting** [comment]
Youtube data api v3 is supported(still premature...) and errors during playing video also fixed.
